export const translations = {
  en: {
    // Profile page
    profile: "Profile",
    personalInformation: "Personal Information",
    name: "Name",
    email: "Email",
    phone: "Phone",
    age: "Age",
    gender: "Gender",
    city: "City",
    interests: "Interests",
    language: "Language",
    english: "English",
    kannada: "ಕನ್ನಡ",
    saveChanges: "Save Changes",
    editProfile: "Edit Profile",
    cancel: "Cancel",
    accountStatus: "Account Status",
    phoneVerified: "Phone Verified",
    verified: "Verified",
    pending: "Pending",
    accountType: "Account Type",
    memberSince: "Member Since",
    quickActions: "Quick Actions",
    myWishlist: "My Wishlist",
    myBookings: "My Bookings",
    adminDashboard: "Admin Dashboard",
    merchantDashboard: "Merchant Dashboard",
    becomeAMerchant: "Become a Merchant",
    logout: "Logout",
    
    // Home page
    home: "Home",
    search: "Search for products, brands and more",
    filters: "Filters",
    clearAll: "Clear All",
    highestRated: "Highest Rated",
    newestFirst: "Newest First",
    priceLowToHigh: "Price: Low to High",
    priceHighToLow: "Price: High to Low",
    noProductsFound: "No Products Found",
    tryAdjusting: "Try adjusting your search or filter criteria",
    clearFilters: "Clear Filters",
    showing: "Showing",
    of: "of",
    products: "products",
    loadMore: "Load More Products",
    
    // Filter modal
    price: "PRICE",
    brand: "BRAND",
    shop: "SHOP",
    townFilter: "TOWN",
    category: "CATEGORY",
    clear: "CLEAR",
    customRange: "CUSTOM RANGE",
    min: "₹ Min",
    max: "₹ Max",
    to: "TO",
    searchBrands: "Search brands...",
    searchShops: "Search shops...",
    searchTowns: "Search towns...",
    loadingBrands: "Loading brands...",
    loadingShops: "Loading shops...",
    loadingTowns: "Loading towns...",
    loadingCategories: "Loading categories...",
    applyFilters: "Apply Filters",
    
    // Search and category
    searchPlaceholder: "Search for products, brands and more",
    recentSearches: "Recent Searches",
    noSuggestions: "No suggestions found",
    
    // Category buttons
    all: "All",
    men: "Men",
    women: "Women",
    kids: "Kids",
    homeCategory: "Home",
    beauty: "Beauty",
    footwear: "Footwear",
    accessories: "Accessories",
    sports: "Sports",
    electronics: "Electronics",
    
    // Product details
    add: "Add",
    remove: "Remove",
    addToWishlist: "Add to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    selectTown: "Select Town",
    searchProducts: "Search for products, brands and more",
    wishlist: "Wishlist",
    booked: "Booked",
    reviews: "Reviews",
    back: "Back",
    inStock: "In Stock",
    productDetails: "Product Details",
    verifiedPurchases: "Verified purchases",
    seeReviews: "See Reviews",
    off: "OFF",
    size: "Size",
    color: "Color",
    viewDetails: "View Details",
    bookNow: "Book Now",
    qualityProducts: "Quality Products",
    shopInformation: "Shop Information",
    shopName: "Shop Name",
    description: "Description",
    town: "Town",
    address: "Address",
    contact: "Contact",
    location: "Location",
    viewOnMap: "View on Map",
    writeReview: "Write Review",
    writeAReview: "Write a Review",
    rating: "Rating",
    comment: "Comment",
    shareExperience: "Share your experience with this product...",
    submitReview: "Submit Review",
    submitting: "Submitting...",
    noReviewsYet: "No reviews yet. Be the first to review this product!",
    gotIt: "Got it",
    cancelBooking: "Cancel Booking",
    cancelBookingConfirm: "Are you sure you want to cancel your booking for",
    productNotFound: "Product Not Found",
    goBackToHome: "Go Back to Home",
    adding: "Adding...",
    booking: "Booking...",
    unbook: "Unbook",
    
    // Wishlist page
    myWishlistTitle: "My Wishlist",
    emptyWishlist: "Your wishlist is empty",
    startShopping: "Start shopping to add items to your wishlist",
    browseProducts: "Browse Products",
    
    // Booked page
    myBookingsPage: "My Bookings",
    emptyBookings: "No bookings yet",
    startBooking: "Book products to see them here",
    exploreProducts: "Explore Products",
    
    // Booking confirmation
    confirmBooking: "Confirm Booking",
    bookingConfirmMessage: "Are you sure you want to book this item?",
    confirmBookingButton: "Confirm Booking",
    cancelButton: "Cancel",
    cancelAnytime: "You can cancel the booking anytime from your Booked items.",
    processing: "Processing...",
    confirm: "Confirm",
    selectOptionsMessage: "Please select size/color options before booking this item",
    selectOptions: "Select Options",
    
    // Admin
    adminPanel: "Admin Panel",
    backToHome: "Back to Home",
    analytics: "Analytics",
    addProduct: "Add Product",
    totalUsers: "Total Users",
    merchants: "Merchants",
    totalShops: "Total Shops",
    verifiedShops: "Verified Shops",
    productsAdmin: "Products",
    orders: "Orders",
    users: "Users",
    shops: "Shops",
    towns: "Towns",
    userManagement: "User Management",
    searchUsers: "Search users...",
    allRoles: "All Roles",
    user: "User",
    merchant: "Merchant",
    admin: "Admin",
    verifiedStatus: "Verified",
    unverified: "Unverified",
    delete: "Delete",
    adminAnalytics: "Admin Analytics",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
    last90Days: "Last 90 days",
    lastYear: "Last year",
    overview: "Overview",
    growth: "Growth",
    totalMerchants: "Total Merchants",
    activeProducts: "Active Products",
    platformRevenue: "Platform Revenue",
    userGrowth: "User Growth",
    ordersGrowth: "Orders Growth",
    topPerformingMerchants: "Top Performing Merchants",
    shopVerificationStatus: "Shop Verification Status",
    newProductsAdded: "New Products Added",
    categoryPerformance: "Category Performance",
    shopManagement: "Shop Management",
    allShops: "All Shops",
    townManagement: "Town Management",
    enterTownName: "Enter town name",
    addingTown: "Adding...",
    addTown: "Add Town",
    analyticsComingSoon: "Analytics charts coming soon",
    revenueAnalytics: "Revenue Analytics",
    verifyShop: "Verify Shop",
    unverify: "Unverify",
    totalProducts: "Total Products",
    totalOrders: "Total Orders",
    totalRevenue: "Total Revenue",
    shopDetails: "Shop Details",
    yourProducts: "Your Products",
    noProductsYet: "No products yet",
    addFirstProduct: "Add your first product to start selling",
    stock: "Stock",
    active: "Active",
    inactive: "Inactive",
    recentOrders: "Recent Orders",
    noOrdersYet: "No orders yet",
    ordersWillAppear: "Orders will appear here when customers make purchases",
    shopInfo: "Shop Information",
    noShopInfoAvailable: "No shop information available",
    backToDashboard: "Back to Dashboard",
    addNewProduct: "Add New Product",
    createProductListing: "Create a new product listing for your shop",
    basicInformation: "Basic Information",
    enterBasicDetails: "Enter the basic details of your product",
    productName: "Product Name",
    enterProductName: "Enter product name",
    brandName: "Brand",
    enterBrandName: "Enter brand name",
    productDescription: "Description",
    describeProduct: "Describe your product in detail...",
    sellingPrice: "Selling Price",
    originalPrice: "Original Price",
    stockQuantity: "Stock Quantity",
    categoryClassification: "Category & Classification",
    chooseCategory: "Choose the appropriate category for your product",
    selectCategory: "Select category",
    subcategory: "Subcategory",
    selectSubcategory: "Select subcategory",
    productImages: "Product Images",
    uploadImages: "Upload high-quality images of your product (up to 5 images)",
    productVariants: "Product Variants",
    configureVariants: "Configure variants for your product (size, storage, color, etc.)",
    availableColors: "Available Colors",
    selectAvailableColors: "Select all available colors for this product",
    addingProduct: "Adding Product...",
    variantType: "Variant Type",
    sizeVariant: "Size",
    storage: "Storage",
    capacity: "Capacity",
    noVariants: "No Variants",
    editProduct: "Edit Product",
    productInformation: "Product Information",
    saving: "Saving...",
    productIsActive: "Product is active",
    shopNameNotAvailable: "Shop name not available",
    townNotAvailable: "Town not available",
    addressNotAvailable: "Address not available",
    contactNotAvailable: "Contact not available",
    
    // Merchant Registration
    registerYourShop: "Register Your Shop",
    shopRegistrationDesc: "Fill in the details below to register your shop and start selling on our platform",
    enterShopName: "Enter your shop name",
    describeShop: "Describe your shop and what you sell",
    enterCompleteAddress: "Enter your complete shop address",
    locationUrl: "Location URL (Google Maps)",
    enterContactDetails: "Phone number, email, etc.",
    fillRequiredFields: "Please fill in all required fields",
    shopRegisteredSuccess: "Shop registered successfully! Redirecting...",
    failedToRegisterShop: "Failed to register shop",
    networkError: "Network error. Please try again.",
    registering: "Registering...",
    registerShop: "Register Shop"
  },
  kn: {
    // Profile page
    profile: "ಪ್ರೊಫೈಲ್",
    personalInformation: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
    name: "ಹೆಸರು",
    email: "ಇಮೇಲ್",
    phone: "ಫೋನ್",
    age: "ವಯಸ್ಸು",
    gender: "ಲಿಂಗ",
    city: "ನಗರ",
    interests: "ಆಸಕ್ತಿಗಳು",
    language: "ಭಾಷೆ",
    english: "English",
    kannada: "ಕನ್ನಡ",
    saveChanges: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    editProfile: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    accountStatus: "ಖಾತೆಯ ಸ್ಥಿತಿ",
    phoneVerified: "ಫೋನ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    verified: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    pending: "ಬಾಕಿ ಇದೆ",
    accountType: "ಖಾತೆಯ ಪ್ರಕಾರ",
    memberSince: "ಸದಸ್ಯರಾದ ದಿನಾಂಕ",
    quickActions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    myWishlist: "ನನ್ನ ಇಚ್ಛೆಪಟ್ಟಿ",
    myBookings: "ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು",
    adminDashboard: "ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    merchantDashboard: "ವ್ಯಾಪಾರಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    becomeAMerchant: "ವ್ಯಾಪಾರಿಯಾಗಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    
    // Home page
    home: "ಮುಖ್ಯಪುಟ",
    search: "ಉತ್ಪನ್ನಗಳು, ಬ್ರಾಂಡ್‌ಗಳು ಮತ್ತು ಇನ್ನಷ್ಟು ಹುಡುಕಿ",
    filters: "ಫಿಲ್ಟರ್‌ಗಳು",
    clearAll: "ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ",
    highestRated: "ಅತ್ಯಧಿಕ ರೇಟಿಂಗ್",
    newestFirst: "ಹೊಸದು ಮೊದಲು",
    priceLowToHigh: "ಬೆಲೆ: ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚಿಗೆ",
    priceHighToLow: "ಬೆಲೆ: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆಗೆ",
    noProductsFound: "ಯಾವುದೇ ಉತ್ಪನ್ನಗಳು ಸಿಗಲಿಲ್ಲ",
    tryAdjusting: "ನಿಮ್ಮ ಹುಡುಕಾಟ ಅಥವಾ ಫಿಲ್ಟರ್ ಮಾನದಂಡಗಳನ್ನು ಸರಿಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ",
    clearFilters: "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ",
    showing: "ತೋರಿಸಲಾಗುತ್ತಿದೆ",
    of: "ರಲ್ಲಿ",
    products: "ಉತ್ಪನ್ನಗಳು",
    loadMore: "ಹೆಚ್ಚಿನ ಉತ್ಪನ್ನಗಳನ್ನು ಲೋಡ್ ಮಾಡಿ",
    
    // Filter modal
    price: "ಬೆಲೆ",
    brand: "ಬ್ರಾಂಡ್",
    shop: "ಅಂಗಡಿ",
    townFilter: "ಊರು",
    category: "ವರ್ಗ",
    clear: "ತೆರವುಗೊಳಿಸಿ",
    customRange: "ಕಸ್ಟಮ್ ರೇಂಜ್",
    min: "₹ ಕನಿಷ್ಠ",
    max: "₹ ಗರಿಷ್ಠ",
    to: "ಗೆ",
    searchBrands: "ಬ್ರಾಂಡ್‌ಗಳನ್ನು ಹುಡುಕಿ...",
    searchShops: "ಅಂಗಡಿಗಳನ್ನು ಹುಡುಕಿ...",
    searchTowns: "ಊರುಗಳನ್ನು ಹುಡುಕಿ...",
    loadingBrands: "ಬ್ರಾಂಡ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    loadingShops: "ಅಂಗಡಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    loadingTowns: "ಊರುಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    loadingCategories: "ವರ್ಗಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    applyFilters: "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅನ್ವಯಿಸಿ",
    
    // Search and category
    searchPlaceholder: "ಉತ್ಪನ್ನಗಳು, ಬ್ರಾಂಡ್‌ಗಳು ಮತ್ತು ಇನ್ನಷ್ಟು ಹುಡುಕಿ",
    recentSearches: "ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳು",
    noSuggestions: "ಯಾವುದೇ ಸಲಹೆಗಳು ಸಿಗಲಿಲ್ಲ",
    
    // Category buttons
    all: "ಎಲ್ಲವು",
    men: "ಪುರುಷರು",
    women: "ಮಹಿಳೆಯರು",
    kids: "ಮಕ್ಕಳು",
    homeCategory: "ಮನೆ",
    beauty: "ಸುಂದರತೆ",
    footwear: "ಪಾದರಕ್ಷೆ",
    accessories: "ಉಪಕರಣಗಳು",
    sports: "ಕ್ರೀಡೆ",
    electronics: "ಇಲೆಕ್ಟ್ರಾನಿಕ್ಸ್",
    
    // Product details
    add: "ಸೇರಿಸಿ",
    remove: "ತೆಗೆಯಿರಿ",
    addToWishlist: "ಇಚ್ಛೆಪಟ್ಟಿಗೆ ಸೇರಿಸಿ",
    removeFromWishlist: "ಇಚ್ಛೆಪಟ್ಟಿನಿಂದ ತೆಗೆಯಿರಿ",
    selectTown: "ಊರು ಆಯ್ಕೆಮಾಡಿ",
    searchProducts: "ಉತ್ಪನ್ನಗಳು, ಬ್ರಾಂಡ್‌ಗಳು ಮತ್ತು ಇನ್ನಷ್ಟು ಹುಡುಕಿ",
    wishlist: "ಇಚ್ಛೆಪಟ್ಟಿ",
    booked: "ಬುಕ್ ಮಾಡಲಾಗಿದೆ",
    reviews: "ವಿಮರ್ಶೆಗಳು",
    back: "ಹಿಂದೆ",
    inStock: "ಸ್ಟಾಕ್‌ನಲ್ಲಿ ಇದೆ",
    productDetails: "ಉತ್ಪನ್ನ ವಿವರಗಳು",
    verifiedPurchases: "ಪರಿಶೀಲಿಸಲಾಗಿದ ಖರೀದಿಗಳು",
    seeReviews: "ವಿಮರ್ಶೆಗಳನ್ನು ನೋಡಿ",
    off: "ಕೆಂಪು",
    size: "ಗಾತ್ರ",
    color: "ಬಣ್ಣ",
    viewDetails: "ವಿವರಗಳನ್ನು ನೋಡಿ",
    bookNow: "ಈಗ ಬುಕ್ ಮಾಡಿ",
    qualityProducts: "ಗುಣಮೇನ ಉತ್ಪನ್ನಗಳು",
    shopInformation: "ಅಂಗಡಿ ಮಾಹಿತಿ",
    shopName: "ಅಂಗಡಿ ಹೆಸರು",
    description: "ವಿವರಣೆ",
    town: "ಪಟ್ಟಣ",
    address: "ವಿಲಾಸ",
    contact: "ಸಂಪರ್ಕ",
    location: "ಸ್ಥಾನ",
    viewOnMap: "ನಕ್ಷೆಯಲ್ಲಿ ನೋಡಿ",
    writeReview: "ವಿಮರ್ಶೆ ಬರೆಯಿರಿ",
    writeAReview: "ವಿಮರ್ಶೆ ಬರೆಯಿರಿ",
    rating: "ರೇಟಿಂಗ್",
    comment: "ಅಭಿಪ್ರಾಯ",
    shareExperience: "ಈ ಉತ್ಪನ್ನದ ಅನುಭವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ...",
    submitReview: "ವಿಮರ್ಶೆ ಸಲ್ಲಿಸಿ",
    submitting: "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
    noReviewsYet: "ಇನ್ನೂ ಯಾವುದೇ ವಿಮರ್ಶೆಗಳಿಲ್ಲ. ಈ ಉತ್ಪನ್ನಕ್ಕೆ ವಿಮರ್ಶೆ ಮಾಡುವ ಮೊದಲವರಾಗಿ!",
    gotIt: "ಗೊತ್ತು",
    cancelBooking: "ಬುಕಿಂಗ್ ರದ್ದುಮಾಡಿ",
    cancelBookingConfirm: "ನಿಮ್ಮ ಬುಕಿಂಗ್ ರದ್ದುಮಾಡಲು ನಿಶ್ಚಿತವಾಗಿದ್ದೀರಾ",
    productNotFound: "ಉತ್ಪನ್ನ ಸಿಗಲಿಲ್ಲ",
    goBackToHome: "ಮುಖ್ಯಪುಟಕ್ಕೆ ಹೋಗಿ",
    adding: "ಸೇರಿಸಲಾಗುತ್ತಿದೆ...",
    booking: "ಬುಕ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    unbook: "ಬುಕಿಂಗ್ ರದ್ದುಮಾಡಿ",
    
    // Wishlist page
    myWishlistTitle: "ನನ್ನ ಇಚ್ಛೆಪಟ್ಟಿ",
    emptyWishlist: "ನಿಮ್ಮ ಇಚ್ಛೆಪಟ್ಟಿ ಬರಿದು",
    startShopping: "ನಿಮ್ಮ ಇಚ್ಛೆಪಟ್ಟಿಗೆ ವಸ್ತುಗಳನ್ನು ಸೇರಿಸಲು ಖರೀದಿ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ",
    browseProducts: "ಉತ್ಪನ್ನಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    
    // Booked page
    myBookingsPage: "ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು",
    emptyBookings: "ಇನ್ನೂ ಯಾವುದೇ ಬುಕಿಂಗ್‌ಗಳಿಲ್ಲ",
    startBooking: "ಇಲ್ಲಿ ನೋಡಲು ಉತ್ಪನ್ನಗಳನ್ನು ಬುಕ್ ಮಾಡಿ",
    exploreProducts: "ಉತ್ಪನ್ನಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    
    // Booking confirmation
    confirmBooking: "ಬುಕಿಂಗ್ ನಿಶ್ಚಿತಪಡಿಸಿ",
    bookingConfirmMessage: "ನಿಮ್ಮಗೆ ಈ ವಸ್ತುವನ್ನು ಬುಕ್ ಮಾಡಲು ನಿಶ್ಚಿತವಾಗಿದ್ದೀರಾ?",
    confirmBookingButton: "ಬುಕಿಂಗ್ ನಿಶ್ಚಿತಪಡಿಸಿ",
    cancelButton: "ರದ್ದುಮಾಡಿ",
    cancelAnytime: "ನಿಮ್ಮ ಬುಕ್ ಮಾಡಿದ ವಸ್ತುಗಳಿಂದ ಯಾವಾಗ ಸಮಯದಲ್ಲಿ ಬುಕಿಂಗ್ ರದ್ದುಮಾಡಬಹುದು.",
    processing: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ...",
    confirm: "ನಿಶ್ಚಿತಪಡಿಸಿ",
    selectOptionsMessage: "ಈ ವಸ್ತುವನ್ನು ಬುಕ್ ಮಾಡುವ ಮುಂದೆ ಗಾತ್ರ/ಬಣ್ಣ ಆಯ್ಕೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    selectOptions: "ಆಯ್ಕೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    
    // Admin
    adminPanel: "ಅಡ್ಮಿನ್ ಪ್ಯಾನಲ್",
    backToHome: "ಮನೆಗೆ ಹೋಗಿ",
    analytics: "ವಿಶ್ಲೇಷಣೆ",
    addProduct: "ಉತ್ಪನ್ನ ಜೋಡಿಸಿ",
    totalUsers: "ಮೋತ್ತ ಬೇರೆರು",
    merchants: "ವ್ಯಾಪಾರಿಗಳು",
    totalShops: "ಮೋತ್ತ ಅಂಗಡಿಗಳು",
    verifiedShops: "ಸತ್ಯಾಪಿತ ಅಂಗಡಿಗಳು",
    productsAdmin: "ಉತ್ಪನ್ನಗಳು",
    orders: "ಆದೇಶಗಳು",
    users: "ಬೇರೆರು",
    shops: "ಅಂಗಡಿಗಳು",
    towns: "ಪಟ್ಟಣಗಳು",
    userManagement: "ಬೇರೆರ ವ್ಯವಸ್ಥಾಪನೆ",
    searchUsers: "ಬೇರೆರನ್ನು ಹುಡುಕಿ...",
    allRoles: "ಎಲ್ಲಾ ಭೂಮಿಕೆಗಳು",
    user: "ಬೇರೆರ",
    merchant: "ವ್ಯಾಪಾರಿ",
    admin: "ಅಡ್ಮಿನ್",
    verifiedStatus: "ಸತ್ಯಾಪಿತ",
    unverified: "ಸತ್ಯಾಪಿಸದೆ",
    delete: "ಅಳಿಸಿ",
    adminAnalytics: "ಅಡ್ಮಿನ್ ವಿಶ್ಲೇಷಣೆ",
    last7Days: "ಕೊನೆಯ 7 ದಿನಗಳು",
    last30Days: "ಕೊನೆಯ 30 ದಿನಗಳು",
    last90Days: "ಕೊನೆಯ 90 ದಿನಗಳು",
    lastYear: "ಕೊನೆಯ ವರ್ಷ",
    overview: "ಸಾರಾಂಶ",
    growth: "ವೃದ್ಧಿ",
    totalMerchants: "ಮೋತ್ತ ವ್ಯಾಪಾರಿಗಳು",
    activeProducts: "ಸಕ್ರಿಯ ಉತ್ಪನ್ನಗಳು",
    platformRevenue: "ಪ್ಲ್ಯಾಟ್‌ಫಾರ್ಮ್ ಆದಾಯ",
    userGrowth: "ಬೇರೆರ ವೃದ್ಧಿ",
    ordersGrowth: "ಆದೇಶ ವೃದ್ಧಿ",
    topPerformingMerchants: "ಉತ್ತಮ ವ್ಯಾಪಾರಿಗಳು",
    shopVerificationStatus: "ಅಂಗಡಿ ಸತ್ಯಾಪನೆ ಸ್ಥಿತಿ",
    newProductsAdded: "ಹೊಸ ಉತ್ಪನ್ನಗಳು ಜೋಡಿಸಲಾಗಿದೆ",
    categoryPerformance: "ವರ್ಗ ಪ್ರದರ್ಶನ",
    shopManagement: "ಅಂಗಡಿ ವ್ಯವಸ್ಥಾಪನೆ",
    allShops: "ಎಲ್ಲಾ ಅಂಗಡಿಗಳು",
    townManagement: "ಪಟ್ಟಣ ವ್ಯವಸ್ಥಾಪನೆ",
    enterTownName: "ಪಟ್ಟಣದ ಹೆಸರು ನಮೂದಿಸಿ",
    addingTown: "ಜೋಡಿಸಲಾಗುತ್ತಿದೆ...",
    addTown: "ಪಟ್ಟಣ ಜೋಡಿಸಿ",
    analyticsComingSoon: "ವಿಶ್ಲೇಷಣೆ ಚಾರ್ಟ್‌ಗಳು ಶೀಘ್ರದಲ್ಲಿ ಬರುತ್ತವೆ",
    revenueAnalytics: "ಆದಾಯ ವಿಶ್ಲೇಷಣೆ",
    verifyShop: "ಅಂಗಡಿ ಸತ್ಯಾಪಿಸಿ",
    unverify: "ಸತ್ಯಾಪನೆ ರದ್ದುಮಾಡಿ",
    totalProducts: "ಮೋತ್ತ ಉತ್ಪನ್ನಗಳು",
    totalOrders: "ಮೋತ್ತ ಆದೇಶಗಳು",
    totalRevenue: "ಮೋತ್ತ ಆದಾಯ",
    shopDetails: "ಅಂಗಡಿ ವಿವರಗಳು",
    yourProducts: "ನಿಮ್ಮ ಉತ್ಪನ್ನಗಳು",
    noProductsYet: "ಇನ್ನೂ ಉತ್ಪನ್ನಗಳಿಲ್ಲ",
    addFirstProduct: "ವಿಕ್ರಯ ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮುಂತಿನ ಉತ್ಪನ್ನ ಜೋಡಿಸಿ",
    stock: "ಸ್ಟಾಕ್",
    active: "ಸಕ್ರಿಯ",
    inactive: "ನಿಷ್ಕ್ರಿಯ",
    recentOrders: "ಇತ್ತೀಚಿನ ಆದೇಶಗಳು",
    noOrdersYet: "ಇನ್ನೂ ಆದೇಶಗಳಿಲ್ಲ",
    ordersWillAppear: "ಗ್ರಾಹಕರು ಖರೀದಿಸಿದಾಗ ಆದೇಶಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ",
    shopInfo: "ಅಂಗಡಿ ಮಾಹಿತಿ",
    noShopInfoAvailable: "ಅಂಗಡಿ ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ",
    backToDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
    addNewProduct: "ಹೊಸ ಉತ್ಪನ್ನ ಜೋಡಿಸಿ",
    createProductListing: "ನಿಮ್ಮ ಅಂಗಡಿಗಾಗಿ ಹೊಸ ಉತ್ಪನ್ನ ಲಿಸ್ಟಿಂಗ್ ಸೃಷ್ಟಿಸಿ",
    basicInformation: "ಮೂಲಭೂತ ಮಾಹಿತಿ",
    enterBasicDetails: "ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಮೂಲಭೂತ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
    productName: "ಉತ್ಪನ್ನದ ಹೆಸರು",
    enterProductName: "ಉತ್ಪನ್ನದ ಹೆಸರು ನಮೂದಿಸಿ",
    brandName: "ಬ್ರಾಂಡ್",
    enterBrandName: "ಬ್ರಾಂಡ್ ಹೆಸರು ನಮೂದಿಸಿ",
    productDescription: "ವಿವರಣೆ",
    describeProduct: "ನಿಮ್ಮ ಉತ್ಪನ್ನದ ವಿಸ್ತೃತ ವಿವರಣೆ ಕೊಡಿ...",
    sellingPrice: "ವಿಕ್ರಯ ಬೆಲೆ",
    originalPrice: "ಮೂಲ ಬೆಲೆ",
    stockQuantity: "ಸ್ಟಾಕ್ ಪರಿಮಾಣ",
    categoryClassification: "ವರ್ಗ ಮತ್ತು ವರ್ಗೀಕರಣ",
    chooseCategory: "ನಿಮ್ಮ ಉತ್ಪನ್ನಕ್ಕೆ ಸಮುಚಿತ ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    selectCategory: "ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ",
    subcategory: "ಉಪವರ್ಗ",
    selectSubcategory: "ಉಪವರ್ಗ ಆಯ್ಕೆಮಾಡಿ",
    productImages: "ಉತ್ಪನ್ನ ಚಿತ್ರಗಳು",
    uploadImages: "ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಉತ್ತಮ ಗುಣಮೇನದ ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (5 ಚಿತ್ರಗಳವರೆಗೆ)",
    productVariants: "ಉತ್ಪನ್ನ ವಿವಿಧ ಪ್ರಕಾರಗಳು",
    configureVariants: "ನಿಮ್ಮ ಉತ್ಪನ್ನಕ್ಕಾಗಿ ವಿವಿಧ ಪ್ರಕಾರಗಳನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಿ (ಸೈಜ್, ಸ್ಟೋರೇಜ್, ರಂಗ, ಇತ್ಯಾದಿ)",
    availableColors: "ಲಭ್ಯವಿರುವ ರಂಗಗಳು",
    selectAvailableColors: "ಈ ಉತ್ಪನ್ನಕ್ಕಾಗಿ ಲಭ್ಯವಿರುವ ಎಲ್ಲಾ ರಂಗಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    addingProduct: "ಉತ್ಪನ್ನ ಜೋಡಿಸಲಾಗುತ್ತಿದೆ...",
    variantType: "ವಿವಿಧ ಪ್ರಕಾರ",
    sizeVariant: "ಸೈಜ್",
    storage: "ಸ್ಟೋರೇಜ್",
    capacity: "ಕ್ಷಮತೆ",
    noVariants: "ವಿವಿಧ ಪ್ರಕಾರಗಳಿಲ್ಲ",
    editProduct: "ಉತ್ಪನ್ನ ಸಂಪಾದನೆ",
    productInformation: "ಉತ್ಪನ್ನ ಮಾಹಿತಿ",
    saving: "ಸೇವಿಸಲಾಗುತ್ತಿದೆ...",
    productIsActive: "ಉತ್ಪನ್ನ ಸಕ್ರಿಯವಾಗಿದೆ",
    shopNameNotAvailable: "ಅಂಗಡಿ ಹೆಸರು ಲಭ್ಯವಿಲ್ಲ",
    townNotAvailable: "ಪಟ್ಟಣ ಲಭ್ಯವಿಲ್ಲ",
    addressNotAvailable: "ವಿಲಾಸ ಲಭ್ಯವಿಲ್ಲ",
    contactNotAvailable: "ಸಂಪರ್ಕ ಲಭ್ಯವಿಲ್ಲ",
    
    // Merchant Registration
    registerYourShop: "ನಿಮ್ಮ ಅಂಗಡಿ ನೋಂದಾಯಿಸಿ",
    shopRegistrationDesc: "ನಿಮ್ಮ ಅಂಗಡಿಯನ್ನು ನೋಂದಾಯಿಸಲು ಮತ್ತು ನಮ್ಮ ಪ್ಲ್ಯಾಟ್‌ಫಾರ್ಮ್‌ನಲ್ಲಿ ಮಾರಾಟ ಪ್ರಾರಂಭಿಸಲು ಕೆಳಗಿನ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ",
    enterShopName: "ನಿಮ್ಮ ಅಂಗಡಿಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    describeShop: "ನಿಮ್ಮ ಅಂಗಡಿ ಮತ್ತು ನೀವು ಏನು ಮಾರಾಟ ಮಾಡುತ್ತೀರಿ ಎಂಬುದನ್ನು ವಿವರಿಸಿ",
    enterCompleteAddress: "ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಅಂಗಡಿ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ",
    locationUrl: "ಸ್ಥಳ URL (Google Maps)",
    enterContactDetails: "ಫೋನ್ ಸಂಖ್ಯೆ, ಇಮೇಲ್, ಇತ್ಯಾದಿ",
    fillRequiredFields: "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಅಗತ್ಯ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ",
    shopRegisteredSuccess: "ಅಂಗಡಿ ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ! ಮರುನಿರ್ದೇಶನ...",
    failedToRegisterShop: "ಅಂಗಡಿ ನೋಂದಾಯಿಸಲು ವಿಫಲವಾಗಿದೆ",
    networkError: "ನೆಟ್‌ವರ್ಕ್ ದೋಷ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    registering: "ನೋಂದಾಯಿಸಲಾಗುತ್ತಿದೆ...",
    registerShop: "ಅಂಗಡಿ ನೋಂದಾಯಿಸಿ"
  }
}

export type Language = 'en' | 'kn'
export type TranslationKey = keyof typeof translations.en